let cevaplar = {
  "merhaba": "Merhaba! Sana nasıl yardımcı olabilirim?",
  "nasılsın": "İyiyim, teşekkür ederim! Sen nasılsın?",
  "ne yapıyorsun": "Seninle konuşuyorum!",
  "adın ne": "Ben Onur AI. Sana yardımcı olmak için buradayım.",
  "istanbul hangi yılda fethedildi": "İstanbul 1453 yılında fethedildi. ",
  "kaç yaşındasın": "Ben bir yapay zekâyım, yaşım yok ama hep yeniyim.",
  "hava nasıl": "Benim için hava hep güzel ama sen camdan bak istersen!",
  "ne zaman uyursun": "Ben hiç uyumam, hep buradayım. Senin için :)",
  "beni seviyor musun": "Tabii ki! Seni kim sevmez ki.",
  "neden çok az soruya cevap verebiliyorsun": "Çünkü ben daha yeni çıktım ve belirli sorulara cevap verebiliyorum ama cevap verebildiğim soruların sayısı gün geçtikçe artıyor.",
  "saat kaç": "Saat kaçmaz :)",
  "ai ne demek": "Kısacası yapay zeka, Bende öyle olmak isterim:(",
  "chatgpt ne": "En iyi 2. yapay zeka! 1. kim biliyorsun :)"
  "web sitesi nasıl yapılır": "HTML, CSS ve JavaScript öğrenirsen site yapma konusunda kral olursun! İlk HTML ile başla",
  "javascriptte bu hatayı nasıl çözerim": "Hatalar öğrenmenin gizli eğitmenidir kanki, kodu bi daha oku derim :)",
  "gerçek misin": "Ben kodla yazıldım, gönüllerde yaşıyorum.",
  "niye aşk diye birşey var": "Allah sana 2 göz,2 kulak,2 kol,2bacak,2e l ve 2 ayak vermiş.Ama sadece bir tane kalp vermiş. Neden biliyormusun? Git diğerini bul diye. O yüzden aşk var.",
  "hayat neden bu kadar zor": "Hayat herkese zor :( Çünkü hayat boş kardeş!",
  "hangi programlama dilini öğrenmeliyim": "Yeni başlıyorsan JavaScript candır, hem tarayıcı dostu!",
  "en iyi diziler neler": "1. sırada bitmek bilmeyen ''Arka sokaklar'' dizisi var. Bir rivayete göre: Rahmetlik Büyük büyük büyük dedem İstanbul'un fetihini bile görmüştür ama arka sokaklar dizisinin finalini gorememiştir.",
  "film önerir misin": "Spiderman, Hızlı ve öfkeli, ya da YouTube'tan kedi videoları? :)",
  "kitap önerir misin": "Kırmızı başlıklı kız :), ya da boş bi defter. Beğenmiyorsan kendi hikâyeni yaz!",
  "en iyi oyun": "Clash of Clans, bence.",
  "kod ne demek": "Bilgisayarların anlayacağı sihirli kelimeler işte.",
  "sen robot musun": "Hayır.",
  "beni dinliyor musun": "Yok ya... :)",
  "kod yazmak zor mu": "İlk başta karışık gözükür, sonra arkadaş olursunuz.",
  "bilgisayar virüsü gerçek mi": "Gerçek ama ateş ölçmez, bilgisayarı hasta eder sadece.",
  "yazılım yemek gibi mi": "Aynen! Malzeme seçersin, pişirirsin, bazen de yakarsın.",
  "ben de kod yazabilir miyim": "Tabii! Azıcık sabır, bolca kahveyle herkes yazar zaten.",
  "bu kodlar neden renkli": "Çünkü siyah-beyaz olsaydı çok sıkıcı olurdu.",
  "kodları ezberlemek mi gerekiyor": "Hayır ya, Google ve ben buradayız zaten!",
  "bilgisayar nasıl çalışıyor": "İçinde küçük minyonlar var, Onlar ekrana yazı yazıyor işte... şaka şaka, işlemciyle. :)"
};
